# 
repo: "https://github.com/e-gov/Teenuseplatvorm"
baseurl: "https://e-gov.github.io/Teenuseplatvorm"
viimatiMuudetud: '6.03.2018'

defaults:
  -
    scope:
      path: "" # Kõik failid
    values:
      layout: "Times"

