# 
repo: "https://github.com/e-gov/Proto"
baseurl: "https://e-gov.github.io/Proto"

defaults:
  -
    scope:
      path: "" # Kõik failid
    values:
      layout: "Times"
    page:
      header: true  

